using GodotSharp.DI.Generator.Internal.Coding;

namespace GodotSharp.DI.Generator.Internal.Helpers;

internal class SourceGenHelper
{
    public static void AppendFileHeader(CodeFormatter f)
    {
        f.AppendLine("// <auto-generated>");
        f.AppendLine("//     This code was generated by GodotSharp.DI.SourceGenerator.");
        f.AppendLine(
            "//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated."
        );
        f.AppendLine("// </auto-generated>");
        f.AppendLine();
        f.AppendLine("#nullable enable");
        f.AppendLine();
    }
}
