<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="GodotSharpDI.Runtime.Tests" />
    <InternalsVisibleTo Include="GodotSharpDI.SourceGenerator.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GodotSharpDI.Abstractions\GodotSharpDI.Abstractions.csproj" />
  </ItemGroup>
</Project>
