using System;
using System.Collections.Generic;

namespace GodotSharpDI.Runtime;

/// <summary>
/// Executes dependency injection with separate try-catch blocks for assignment,
/// ready callback, and failure callback. Replaces the inline try-catch pattern
/// previously generated by InjectionGenerator.
/// </summary>
public static class InjectionExecutor
{
    /// <summary>
    /// Execute injection for a single [Inject] member.
    /// </summary>
    /// <typeparam name="T">The injected member type.</typeparam>
    /// <param name="assign">
    /// Assignment action: sets the member field/property and ready flag.
    /// Example: <c>v => { _field ??= v; IsFieldReady = true; }</c>
    /// </param>
    /// <param name="value">
    /// The resolved value, or null if resolution failed.
    /// </param>
    /// <param name="readyCallback">
    /// Optional callback invoked on success (OnXxxInjectionReady). Null if not configured.
    /// </param>
    /// <param name="failedCallback">
    /// Optional callback invoked on failure (OnXxxInjectionFailed). Null if not configured.
    /// </param>
    /// <param name="callbackList">
    /// WaitFor callback list. Each entry is invoked with true (success) or false (failure).
    /// The list is cleared after all callbacks are invoked.
    /// </param>
    /// <param name="onDependencyResolved">
    /// Called after injection completes. Typically calls OnDependencyResolved&lt;T&gt;().
    /// </param>
    /// <param name="typeName">The containing type name, for error reporting.</param>
    /// <param name="memberName">The member name, for error reporting.</param>
    public static void Execute<T>(
        Action<T> assign,
        T? value,
        Action<T>? readyCallback,
        Action? failedCallback,
        List<Action<bool>> callbackList,
        Action onDependencyResolved,
        string typeName,
        string memberName) where T : class
    {
        if (value is not null)
        {
            // Try-catch for assignment
            try
            {
                assign(value);
            }
            catch (Exception ex)
            {
                ErrorReporter.ReportInjectionAssignFailed(
                    typeName, memberName, typeof(T).Name, ex.Message);
            }

            // Separate try-catch for ready callback
            try
            {
                readyCallback?.Invoke(value);
            }
            catch (Exception ex)
            {
                ErrorReporter.ReportInjectionReadyCallbackFailed(
                    typeName, memberName, typeof(T).Name, ex.Message);
            }
        }
        else
        {
            // Try-catch for failure callback
            try
            {
                failedCallback?.Invoke();
            }
            catch (Exception ex)
            {
                ErrorReporter.ReportInjectionFailedCallbackFailed(
                    typeName, memberName, typeof(T).Name, ex.Message);
            }
        }

        // Notify WaitFor callbacks
        var resolved = value is not null;
        foreach (var cb in callbackList)
            cb.Invoke(resolved);
        callbackList.Clear();

        onDependencyResolved();
    }
}
