using System;
using System.Collections.Generic;

namespace GodotSharpDI.Runtime;

/// <summary>
/// Executes dependency injection with separate try-catch blocks for assignment,
/// ready callback, and failure callback. Replaces the inline try-catch pattern
/// previously generated by InjectionGenerator.
/// </summary>
public static class InjectionExecutor
{
    /// <summary>
    /// Execute injection for a single [Inject] member.
    /// </summary>
    /// <typeparam name="T">The injected member type.</typeparam>
    /// <param name="assign">
    /// Assignment action: sets the member field/property and ready flag.
    /// Example: <c>v => { _field ??= v; IsFieldReady = true; }</c>
    /// </param>
    /// <param name="value">
    /// The resolved value, or null if resolution failed.
    /// </param>
    /// <param name="readyCallback">
    /// Optional callback invoked on success (OnXxxInjectionReady). Null if not configured.
    /// </param>
    /// <param name="failedCallback">
    /// Optional callback invoked on failure (OnXxxInjectionFailed). Null if not configured.
    /// </param>
    /// <param name="callbackList">
    /// WaitFor callback list. Each entry is invoked with true (success) or false (failure).
    /// The list is cleared after all callbacks are invoked.
    /// </param>
    /// <param name="onDependencyResolved">
    /// Called after injection completes. Typically calls OnDependencyResolved&lt;T&gt;().
    /// </param>
    /// <param name="typeName">The containing type name, for error reporting.</param>
    /// <param name="memberName">The member name, for error reporting.</param>
    /// <param name="errorOutput">Error output callback. Typically <c>GD.PrintErr</c>.</param>
    public static void Execute<T>(
        Action<T> assign,
        T? value,
        Action<T>? readyCallback,
        Action? failedCallback,
        List<Action<bool>> callbackList,
        Action onDependencyResolved,
        string typeName,
        string memberName,
        Action<string> errorOutput) where T : class
    {
        var assignSucceeded = false;

        if (value is not null)
        {
            // Try-catch for assignment
            try
            {
                assign(value);
                assignSucceeded = true;
            }
            catch (Exception ex)
            {
                ErrorReporter.ReportInjectionAssignFailed(
                    typeName, memberName, typeof(T).Name, ex, errorOutput);
            }

            // Separate try-catch for ready callback (only if assign succeeded)
            if (assignSucceeded)
            {
                try
                {
                    readyCallback?.Invoke(value);
                }
                catch (Exception ex)
                {
                    ErrorReporter.ReportInjectionReadyCallbackFailed(
                        typeName, memberName, typeof(T).Name, ex, errorOutput);
                }
            }
        }
        else
        {
            // Try-catch for failure callback
            try
            {
                failedCallback?.Invoke();
            }
            catch (Exception ex)
            {
                ErrorReporter.ReportInjectionFailedCallbackFailed(
                    typeName, memberName, typeof(T).Name, ex, errorOutput);
            }
        }

        // Notify WaitFor callbacks — only report success if assign actually succeeded
        var resolved = assignSucceeded;
        foreach (var cb in callbackList)
            cb.Invoke(resolved);
        callbackList.Clear();

        onDependencyResolved();
    }
}
