using GodotSharpDI.SourceGenerator.Internal.Data;
using GodotSharpDI.SourceGenerator.Shared;

namespace GodotSharpDI.SourceGenerator.Internal.Helpers;

/// <summary>
/// Code generation helper methods - Reduces code duplication between generators
/// </summary>
internal static class GeneratorHelper
{
    /// <summary>
    /// Begin class declaration (includes auto-generated comment, namespace, and partial class declaration)
    /// </summary>
    public static void BeginClassDeclaration(
        this CodeFormatter f,
        ValidatedTypeInfo validatedType,
        out string fileName
    )
    {
        f.AppendLine("// <auto-generated/>");
        f.AppendLine();
        f.AppendLine("#nullable enable");
        f.AppendLine();
        if (DisplayFormats.GetNamespace(validatedType.Symbol, out var namespaceName))
        {
            f.AppendLine($"namespace {namespaceName};");
            f.AppendLine();
        }
        var className = DisplayFormats.GetClassName(validatedType.Symbol);
        f.AppendLine($"partial class {className}");
        f.BeginBlock();

        fileName = $"{namespaceName}.{validatedType.Symbol.MetadataName}";
    }

    /// <summary>
    /// End class declaration
    /// </summary>
    public static void EndClassDeclaration(this CodeFormatter f)
    {
        f.EndBlock();
    }

    /// <summary>
    /// Add summary and attribute for generated methods that should not be called manually
    /// </summary>
    public static void AppendHiddenMethodCommentAndAttribute(
        this CodeFormatter f,
        string? summary = null
    )
    {
        f.AppendXmlComment("<summary>");
        if (summary is not null)
        {
            f.AppendXmlComment(summary);
        }
        f.AppendXmlComment(
            "This method is managed by the DI framework and should not be called manually."
        );
        f.AppendXmlComment("</summary>");
        f.AppendLine(IdeAttributes.EditorBrowsableNever);
    }

    /// <summary>
    /// Add summary and attribute for generated members that should not be called manually
    /// </summary>
    public static void AppendHiddenMemberCommentAndAttribute(
        this CodeFormatter f,
        string? summary = null
    )
    {
        f.AppendXmlComment("<summary>");
        if (summary is not null)
        {
            f.AppendXmlComment(summary);
        }
        f.AppendXmlComment(
            "This member is managed by the DI framework and should not be called manually."
        );
        f.AppendXmlComment("</summary>");
        f.AppendLine(IdeAttributes.EditorBrowsableNever);
    }

    public static void BeginTryCatch(this CodeFormatter f)
    {
        f.AppendLine("try");
        f.BeginBlock();
    }

    public static void CatchBlock(this CodeFormatter f, string exceptionName)
    {
        f.EndBlock();
        f.AppendLine($"catch ({GlobalNames.Exception} {exceptionName})");
        f.BeginBlock();
    }

    public static void EndTryCatch(this CodeFormatter f)
    {
        f.EndBlock();
    }

    public static void BeginDebugRegion(this CodeFormatter f)
    {
        f.AppendLine("#if DEBUG");
        f.BeginLevel();
        f.AppendLine();
    }

    public static void EndDebugRegion(this CodeFormatter f)
    {
        f.AppendLine();
        f.EndLevel();
        f.AppendLine("#endif");
    }

    public static void BeginStringBuilderAppend(
        this CodeFormatter f,
        string stringBuilderName,
        bool createNew
    )
    {
        var declare = createNew
            ? $"var {stringBuilderName} = new {GlobalNames.StringBuilder}()"
            : $"{stringBuilderName}";
        f.AppendRaw(declare, true);
        f.BeginLevel();
    }

    public static void EndStringBuilderAppend(this CodeFormatter f)
    {
        f.AppendRaw(";");
        f.AppendLine();
        f.EndLevel();
    }

    public static void StringBuilderAppendLine(this CodeFormatter f, string content)
    {
        f.AppendLine();
        f.AppendRaw($".AppendLine($\"{content}\")", true);
    }

    public static void PrintError(this CodeFormatter f, string target)
    {
        f.AppendLine($"{GlobalNames.GodotGD}.PrintErr({target});");
    }

    public static void AppendTypeConstraints(this CodeFormatter f, string typeConstraints)
    {
        f.BeginLevel();
        f.AppendLine(typeConstraints);
        f.EndLevel();
    }
}
