using GodotSharpDI.SourceGenerator.Internal.Data;
using GodotSharpDI.SourceGenerator.Shared;

namespace GodotSharpDI.SourceGenerator.Internal.Helpers;

/// <summary>
/// 代码生成辅助方法 - 减少生成器之间的代码重复
/// </summary>
internal static class GeneratorHelper
{
    /// <summary>
    /// 开始类声明（包含 auto-generated 注释、命名空间和 partial class 声明）
    /// </summary>
    public static void BeginClassDeclaration(
        this CodeFormatter f,
        ValidatedTypeInfo validatedType,
        out string className
    )
    {
        f.AppendLine("// <auto-generated/>");
        f.AppendLine();
        f.AppendLine("#nullable enable");
        f.AppendLine();
        if (DisplayFormats.GetNamespace(validatedType.Symbol, out var namespaceName))
        {
            f.AppendLine($"namespace {namespaceName};");
            f.AppendLine();
        }
        className = DisplayFormats.GetClassName(validatedType.Symbol);
        f.AppendLine($"partial class {className}");
        f.BeginBlock();
    }

    /// <summary>
    /// 结束类声明
    /// </summary>
    public static void EndClassDeclaration(this CodeFormatter f)
    {
        f.EndBlock();
    }

    /// <summary>
    /// 添加不可手动调用的生成方法的简介和特性
    /// </summary>
    public static void AppendHiddenMethodCommentAndAttribute(
        this CodeFormatter f,
        string? summary = null
    )
    {
        f.AppendXmlComment("<summary>");
        if (summary is not null)
        {
            f.AppendXmlComment(summary);
        }
        f.AppendXmlComment(
            "This method is managed by the DI framework and should not be called manually."
        );
        f.AppendXmlComment("</summary>");
        f.AppendLine(IdeAttributes.EditorBrowsableNever);
    }

    /// <summary>
    /// 添加不可手动调用的生成成员的简介和特性
    /// </summary>
    public static void AppendHiddenMemberCommentAndAttribute(
        this CodeFormatter f,
        string? summary = null
    )
    {
        f.AppendXmlComment("<summary>");
        if (summary is not null)
        {
            f.AppendXmlComment(summary);
        }
        f.AppendXmlComment(
            "This member is managed by the DI framework and should not be called manually."
        );
        f.AppendXmlComment("</summary>");
        f.AppendLine(IdeAttributes.EditorBrowsableNever);
    }

    public static void BeginTryCatch(this CodeFormatter f)
    {
        f.AppendLine("try");
        f.BeginBlock();
    }

    public static void CatchBlock(this CodeFormatter f, string exceptionName)
    {
        f.EndBlock();
        f.AppendLine($"catch ({GlobalNames.Exception} {exceptionName})");
        f.BeginBlock();
    }

    public static void EndTryCatch(this CodeFormatter f)
    {
        f.EndBlock();
    }

    public static void BeginDebugRegion(this CodeFormatter f)
    {
        f.AppendLine("#if DEBUG");
        f.BeginBlock();
    }

    public static void EndDebugRegion(this CodeFormatter f)
    {
        f.EndBlock();
        f.AppendLine("#endif");
    }

    public static void BeginStringBuilderAppend(
        this CodeFormatter f,
        string stringBuilderName,
        bool createNew
    )
    {
        var declare = createNew
            ? $"var {stringBuilderName} = new {GlobalNames.StringBuilder}()"
            : $"{stringBuilderName}";
        f.AppendRaw(declare, true);
        f.BeginLevel();
    }

    public static void EndStringBuilderAppend(this CodeFormatter f)
    {
        f.AppendRaw(";");
        f.AppendLine();
        f.EndLevel();
    }

    public static void StringBuilderAppendLine(this CodeFormatter f, string content)
    {
        f.AppendLine();
        f.AppendRaw($".AppendLine($\"{content}\")", true);
    }

    public static void PushWarning(this CodeFormatter f, string target)
    {
        f.AppendLine($"{GlobalNames.GodotGD}.PushWarning({target});");
    }

    public static void PushError(this CodeFormatter f, string target)
    {
        f.AppendLine($"{GlobalNames.GodotGD}.PushError({target});");
    }
}
