using GodotSharp.DI.Generator.Internal.Data;
using GodotSharp.DI.Generator.Internal.Helpers;
using GodotSharp.DI.Shared;
using Microsoft.CodeAnalysis;
using TypeInfo = GodotSharp.DI.Generator.Internal.Data.TypeInfo;

namespace GodotSharp.DI.Generator.Internal.Coding;

/// <summary>
/// Host 代码生成器
/// </summary>
internal static class HostGenerator
{
    public static void Generate(SourceProductionContext context, TypeNode node)
    {
        var type = node.TypeInfo;
        var namespaceName = type.Symbol.ContainingNamespace.ToDisplayString();
        var className = type.Symbol.Name;

        // 生成基础 DI 文件
        GenerateBaseDI(context, type, namespaceName, className);

        // 生成 Host 特定代码
        GenerateHostSpecific(context, type, namespaceName, className);
    }

    private static void GenerateBaseDI(
        SourceProductionContext context,
        TypeInfo type,
        string namespaceName,
        string className
    )
    {
        var f = new CodeFormatter();
        var isNode = type.Symbol.BaseType?.ToDisplayString().Contains("Godot.Node") ?? false;

        f.AppendLine("// <auto-generated/>");
        f.AppendLine($"namespace {namespaceName};");
        f.AppendLine();
        f.AppendLine($"partial class {className}");
        f.BeginBlock();

        if (isNode)
        {
            NodeDIGenerator.GenerateNodeDICode(f, type);
        }

        f.EndBlock();

        context.AddSource($"{className}.DI.g.cs", f.ToString());
    }

    private static void GenerateHostSpecific(
        SourceProductionContext context,
        TypeInfo type,
        string namespaceName,
        string className
    )
    {
        var f = new CodeFormatter();

        f.AppendLine("// <auto-generated/>");
        f.AppendLine($"namespace {namespaceName};");
        f.AppendLine();
        f.AppendLine($"partial class {className}");
        f.BeginBlock();

        // AttachHostServices
        f.AppendLine($"private void AttachHostServices({GlobalNames.IScope} scope)");
        f.BeginBlock();
        {
            foreach (var member in type.Members)
            {
                if (
                    member.Kind == MemberKind.SingletonField
                    || member.Kind == MemberKind.SingletonProperty
                )
                {
                    foreach (var exposedType in member.ExposedTypes)
                    {
                        f.AppendLine(
                            $"scope.RegisterService<{exposedType.ToDisplayString()}>({member.Symbol.Name});"
                        );
                    }
                }
            }
        }
        f.EndBlock();
        f.AppendLine();

        // UnattachHostServices
        f.AppendLine($"private void UnattachHostServices({GlobalNames.IScope} scope)");
        f.BeginBlock();
        {
            foreach (var member in type.Members)
            {
                if (
                    member.Kind == MemberKind.SingletonField
                    || member.Kind == MemberKind.SingletonProperty
                )
                {
                    foreach (var exposedType in member.ExposedTypes)
                    {
                        f.AppendLine(
                            $"scope.UnregisterService<{exposedType.ToDisplayString()}>();"
                        );
                    }
                }
            }
        }
        f.EndBlock();

        f.EndBlock();

        context.AddSource($"{className}.DI.Host.g.cs", f.ToString());
    }
}
