using System.Text;
using GodotSharp.DI.Shared;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace GodotSharp.DI.Generator.Internal.Coding;

internal static class HostGenerator
{
    private static string FormatType(ITypeSymbol type)
    {
        return type.ToDisplayString(DisplayFormats.TypeFormat);
    }

    public static void Generate(SourceProductionContext context, ServiceGraph graph)
    {
        foreach (var host in graph.Hosts)
        {
            var source = GenerateHostSource(host);
            if (source is null)
                continue;

            var hintName = $"{host.Symbol.Name}.DI.Host.g.cs";
            context.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string GenerateHostSource(TypeInfo host)
    {
        var f = new CodeFormatter();

        var ns = host.Namespace;
        var typeName = host.Symbol.Name;

        f.AppendLine("// <auto-generated />");
        f.AppendLine();
        f.AppendLine($"namespace {ns};");
        f.AppendLine();

        f.AppendLine($"partial class {typeName}");
        f.BeginBlock();
        {
            // AttachHostServices
            f.AppendLine(
                $"private void AttachHostServices({TypeNamesGlobal.ScopeInterface} scope)"
            );
            f.BeginBlock();
            {
                foreach (var provided in host.ProvidedServices)
                {
                    var serviceType = FormatType(provided.ServiceType);
                    f.AppendLine($"scope.RegisterService<{serviceType}>({provided.MemberName});");
                }
            }
            f.EndBlock();
            f.AppendLine();

            // UnattachHostServices
            f.AppendLine(
                $"private void UnattachHostServices({TypeNamesGlobal.ScopeInterface} scope)"
            );
            f.BeginBlock();
            {
                foreach (var provided in host.ProvidedServices)
                {
                    var serviceType = FormatType(provided.ServiceType);
                    f.AppendLine($"scope.UnregisterService<{serviceType}>();");
                }
            }
            f.EndBlock();
        }
        f.EndBlock();

        return f.ToString();
    }
}
