using GodotSharp.DI.Generator.Internal.Data;
using GodotSharp.DI.Generator.Internal.Helpers;
using GodotSharp.DI.Shared;
using Microsoft.CodeAnalysis;

namespace GodotSharp.DI.Generator.Internal.Coding;

/// <summary>
/// Service 工厂代码生成器
/// </summary>
internal static class ServiceGenerator
{
    public static void Generate(SourceProductionContext context, TypeNode node)
    {
        var type = node.TypeInfo;
        var f = new CodeFormatter();

        var namespaceName = type.Symbol.ContainingNamespace.ToDisplayString();
        var className = type.Symbol.Name;
        var isTransient = type.Lifetime == ServiceLifetime.Transient;

        f.AppendLine("// <auto-generated/>");
        f.AppendLine($"namespace {namespaceName};");
        f.AppendLine();
        f.AppendLine($"partial class {className}");
        f.BeginBlock();

        if (type.Constructor == null || type.Constructor.Parameters.IsEmpty)
        {
            GenerateParameterlessFactory(f, className, isTransient);
        }
        else
        {
            GenerateParameterizedFactory(f, className, type.Constructor, isTransient);
        }

        f.EndBlock();

        context.AddSource($"{className}.DI.Factory.g.cs", f.ToString());
    }

    private static void GenerateParameterlessFactory(
        CodeFormatter f,
        string className,
        bool isTransient
    )
    {
        var methodName = "CreateService";
        var parameters = isTransient
            ? $"{GlobalNames.IScope} scope, {GlobalNames.Action}<{GlobalNames.Object}> onCreated"
            : $"{GlobalNames.IScope} scope, {GlobalNames.Action}<{GlobalNames.Object}, {GlobalNames.IScope}> onCreated";

        f.AppendLine($"public static void {methodName}({parameters})");
        f.BeginBlock();
        {
            f.AppendLine($"var instance = new {className}();");

            if (isTransient)
            {
                f.AppendLine("onCreated.Invoke(instance);");
            }
            else
            {
                f.AppendLine("onCreated.Invoke(instance, scope);");
            }
        }
        f.EndBlock();
    }

    private static void GenerateParameterizedFactory(
        CodeFormatter f,
        string className,
        ConstructorInfo ctor,
        bool isTransient
    )
    {
        var methodName = "CreateService";
        var parameters = isTransient
            ? $"{GlobalNames.IScope} scope, {GlobalNames.Action}<{GlobalNames.Object}> onCreated"
            : $"{GlobalNames.IScope} scope, {GlobalNames.Action}<{GlobalNames.Object}, {GlobalNames.IScope}> onCreated";

        f.AppendLine($"public static void {methodName}({parameters})");
        f.BeginBlock();
        {
            f.AppendLine($"var remaining = {ctor.Parameters.Length};");
            f.AppendLine();

            // 声明参数变量
            for (int i = 0; i < ctor.Parameters.Length; i++)
            {
                var param = ctor.Parameters[i];
                f.AppendLine($"{param.Type.ToDisplayString()}? p{i} = null;");
            }
            f.AppendLine();

            // 解析依赖
            for (int i = 0; i < ctor.Parameters.Length; i++)
            {
                var param = ctor.Parameters[i];
                f.AppendLine(
                    $"scope.ResolveDependency<{param.Type.ToDisplayString()}>(dependency =>"
                );
                f.BeginBlock();
                {
                    f.AppendLine($"p{i} = dependency;");
                    f.AppendLine("TryCreate();");
                }
                f.EndBlock(");");
            }

            f.AppendLine();
            f.AppendLine("return;");
            f.AppendLine();

            // TryCreate 本地函数
            f.AppendLine("void TryCreate()");
            f.BeginBlock();
            {
                f.AppendLine("if (--remaining == 0)");
                f.BeginBlock();
                {
                    var paramNames = new System.Collections.Generic.List<string>();
                    for (int i = 0; i < ctor.Parameters.Length; i++)
                    {
                        paramNames.Add($"p{i}!");
                    }
                    var paramList = string.Join(", ", paramNames);
                    f.AppendLine($"var instance = new {className}({paramList});");

                    if (isTransient)
                    {
                        f.AppendLine("onCreated.Invoke(instance);");
                    }
                    else
                    {
                        f.AppendLine("onCreated.Invoke(instance, scope);");
                    }
                }
                f.EndBlock();
            }
            f.EndBlock();
        }
        f.EndBlock();
    }
}
