using System.Text;
using GodotSharp.DI.Shared;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace GodotSharp.DI.Generator.Internal.Coding;

internal static class ServiceFactoryGenerator
{
    private static string FormatType(ITypeSymbol type)
    {
        return type.ToDisplayString(DisplayFormats.TypeFormat);
    }

    public static void Generate(SourceProductionContext context, ServiceGraph graph)
    {
        foreach (var service in graph.Services)
        {
            // 没有构造函数（或不需要注入） → 只生成无参工厂
            var source = GenerateFactorySource(service);
            if (source is null)
                continue;

            var hintName = $"{service.Symbol.Name}.DI.Factory.g.cs";
            context.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string GenerateFactorySource(TypeInfo service)
    {
        var f = new CodeFormatter();

        var ns = service.Namespace;
        var typeName = service.Symbol.Name;
        var fullName = FormatType(service.Symbol);

        var ctor = service.Constructor;
        var hasCtor = ctor is not null && ctor.ParameterTypes.Count > 0;

        // ---------------------------
        // 文件头
        // ---------------------------
        f.AppendLine("// <auto-generated />");
        f.AppendLine();
        f.AppendLine($"namespace {ns};");
        f.AppendLine();

        // ---------------------------
        // partial class
        // ---------------------------
        f.AppendLine($"partial class {typeName}");
        f.BeginBlock();
        {
            // ---------------------------
            // CreateService 方法签名
            // ---------------------------
            f.AppendLine(
                $"public static void CreateService({TypeNamesGlobal.ScopeInterface} scope, global::System.Action<global::System.Object> onCreated)"
            );
            f.BeginBlock();
            {
                if (!hasCtor)
                {
                    // ---------------------------
                    // 无参构造
                    // ---------------------------
                    f.AppendLine($"var instance = new {fullName}();");
                    f.AppendLine("onCreated.Invoke(instance);");
                }
                else
                {
                    // ---------------------------
                    // 多参数构造函数
                    // ---------------------------
                    var paramCount = ctor!.ParameterTypes.Count;

                    f.AppendLine($"var remaining = {paramCount};");
                    f.AppendLine();

                    // 临时变量
                    for (int i = 0; i < paramCount; i++)
                    {
                        var pType = FormatType(ctor.ParameterTypes[i]);
                        f.AppendLine($"{pType}? p{i} = default;");
                    }

                    f.AppendLine();

                    // ResolveDependency 调用
                    for (int i = 0; i < paramCount; i++)
                    {
                        var pType = FormatType(ctor.ParameterTypes[i]);

                        f.AppendLine($"scope.ResolveDependency<{pType}>(dependency =>");
                        f.BeginBlock();
                        {
                            f.AppendLine($"p{i} = dependency;");
                            f.AppendLine(
                                "if (global::System.Threading.Interlocked.Decrement(ref remaining) == 0)"
                            );
                            f.BeginBlock();
                            {
                                f.AppendLine("Create();");
                            }
                            f.EndBlock();
                        }
                        f.EndBlock(");");
                        f.AppendLine();
                    }

                    // Create() 方法
                    f.AppendLine("void Create()");
                    f.BeginBlock();
                    {
                        f.AppendRaw($"var instance = new {fullName}(");
                        for (int i = 0; i < paramCount; i++)
                        {
                            if (i > 0)
                                f.AppendRaw(", ");
                            f.AppendRaw($"p{i}!");
                        }
                        f.AppendLine(");");

                        f.AppendLine("onCreated.Invoke(instance);");
                    }
                    f.EndBlock();
                }
            }
            f.EndBlock();
        }
        f.EndBlock();

        return f.ToString();
    }
}
