using System.Linq;
using GodotSharp.DI.Generator.Internal.Data;
using GodotSharp.DI.Generator.Internal.Helpers;
using GodotSharp.DI.Shared;
using Microsoft.CodeAnalysis;
using TypeInfo = GodotSharp.DI.Generator.Internal.Data.TypeInfo;

namespace GodotSharp.DI.Generator.Internal.Coding;

internal static class SourceEmitter
{
    public static void GenerateAll(SourceProductionContext context, DiGraph graph)
    {
        // 生成 Service 工厂
        foreach (var node in graph.ServiceNodes)
        {
            GenerateServiceFactory(context, node);
        }

        // 生成 Host 代码
        foreach (var node in graph.HostNodes)
        {
            GenerateHostCode(context, node);
        }

        // 生成 User 代码
        foreach (var node in graph.UserNodes)
        {
            GenerateUserCode(context, node);
        }

        // 生成 Scope 代码
        foreach (var node in graph.ScopeNodes)
        {
            GenerateScopeCode(context, node, graph);
        }
    }

    private static void GenerateServiceFactory(SourceProductionContext context, TypeNode node)
    {
        var type = node.TypeInfo;
        var f = new CodeFormatter();

        var namespaceName = type.Symbol.ContainingNamespace.ToDisplayString();
        var className = type.Symbol.Name;
        var isTransient = type.Lifetime == ServiceLifetime.Transient;

        f.AppendLine("// <auto-generated/>");
        f.AppendLine($"namespace {namespaceName};");
        f.AppendLine();
        f.AppendLine($"partial class {className}");
        f.BeginBlock();

        if (type.Constructor == null || type.Constructor.Parameters.IsEmpty)
        {
            GenerateParameterlessFactory(f, className, isTransient);
        }
        else
        {
            GenerateParameterizedFactory(f, className, type.Constructor, isTransient);
        }

        f.EndBlock();

        context.AddSource($"{className}.DI.Factory.g.cs", f.ToString());
    }

    private static void GenerateParameterlessFactory(
        CodeFormatter f,
        string className,
        bool isTransient
    )
    {
        var methodName = "CreateService";
        var parameters = isTransient
            ? $"{GlobalNames.IScope} scope, {GlobalNames.Action}<{GlobalNames.Object}> onCreated"
            : $"{GlobalNames.IScope} scope, {GlobalNames.Action}<{GlobalNames.Object}, {GlobalNames.IScope}> onCreated";

        f.AppendLine($"public static void {methodName}({parameters})");
        f.BeginBlock();
        {
            f.AppendLine($"var instance = new {className}();");

            if (isTransient)
            {
                f.AppendLine("onCreated.Invoke(instance);");
            }
            else
            {
                f.AppendLine("onCreated.Invoke(instance, scope);");
            }
        }
        f.EndBlock();
    }

    private static void GenerateParameterizedFactory(
        CodeFormatter f,
        string className,
        ConstructorInfo ctor,
        bool isTransient
    )
    {
        var methodName = "CreateService";
        var parameters = isTransient
            ? $"{GlobalNames.IScope} scope, {GlobalNames.Action}<{GlobalNames.Object}> onCreated"
            : $"{GlobalNames.IScope} scope, {GlobalNames.Action}<{GlobalNames.Object}, {GlobalNames.IScope}> onCreated";

        f.AppendLine($"public static void {methodName}({parameters})");
        f.BeginBlock();
        {
            f.AppendLine($"var remaining = {ctor.Parameters.Length};");
            f.AppendLine();

            // 声明参数变量
            for (int i = 0; i < ctor.Parameters.Length; i++)
            {
                var param = ctor.Parameters[i];
                f.AppendLine($"{param.Type.ToDisplayString()}? p{i} = null;");
            }
            f.AppendLine();

            // 解析依赖
            for (int i = 0; i < ctor.Parameters.Length; i++)
            {
                var param = ctor.Parameters[i];
                f.AppendLine(
                    $"scope.ResolveDependency<{param.Type.ToDisplayString()}>(dependency =>"
                );
                f.BeginBlock();
                {
                    f.AppendLine($"p{i} = dependency;");
                    f.AppendLine("TryCreate();");
                }
                f.EndBlock(");");
            }

            f.AppendLine();
            f.AppendLine("return;");
            f.AppendLine();

            // TryCreate 本地函数
            f.AppendLine("void TryCreate()");
            f.BeginBlock();
            {
                f.AppendLine("if (--remaining == 0)");
                f.BeginBlock();
                {
                    var paramNames = new System.Collections.Generic.List<string>();
                    for (int i = 0; i < ctor.Parameters.Length; i++)
                    {
                        paramNames.Add($"p{i}!");
                    }
                    var paramList = string.Join(", ", paramNames);
                    f.AppendLine($"var instance = new {className}({paramList});");

                    if (isTransient)
                    {
                        f.AppendLine("onCreated.Invoke(instance);");
                    }
                    else
                    {
                        f.AppendLine("onCreated.Invoke(instance, scope);");
                    }
                }
                f.EndBlock();
            }
            f.EndBlock();
        }
        f.EndBlock();
    }

    private static void GenerateHostCode(SourceProductionContext context, TypeNode node)
    {
        var type = node.TypeInfo;
        var namespaceName = type.Symbol.ContainingNamespace.ToDisplayString();
        var className = type.Symbol.Name;

        // 生成基础 DI 文件
        GenerateBaseDI(context, type, namespaceName, className);

        // 生成 Host 特定代码
        GenerateHostSpecific(context, type, namespaceName, className);
    }

    private static void GenerateUserCode(SourceProductionContext context, TypeNode node)
    {
        var type = node.TypeInfo;
        var namespaceName = type.Symbol.ContainingNamespace.ToDisplayString();
        var className = type.Symbol.Name;

        // 生成基础 DI 文件
        if (type.Role == TypeRole.User)
        {
            GenerateBaseDI(context, type, namespaceName, className);
        }

        // 生成 User 特定代码
        GenerateUserSpecific(context, type, namespaceName, className);
    }

    private static void GenerateBaseDI(
        SourceProductionContext context,
        TypeInfo type,
        string namespaceName,
        string className
    )
    {
        var f = new CodeFormatter();
        var isNode = type.Symbol.BaseType?.ToDisplayString().Contains("Godot.Node") ?? false;

        f.AppendLine("// <auto-generated/>");
        f.AppendLine($"namespace {namespaceName};");
        f.AppendLine();
        f.AppendLine($"partial class {className}");
        f.BeginBlock();

        if (isNode)
        {
            GenerateNodeDICode(f, type);
        }
        else
        {
            GenerateNonNodeDICode(f, type);
        }

        f.EndBlock();

        context.AddSource($"{className}.DI.g.cs", f.ToString());
    }

    private static void GenerateNodeDICode(CodeFormatter f, TypeInfo type)
    {
        f.AppendLine($"private {GlobalNames.IScope}? _serviceScope;");
        f.AppendLine();

        // GetServiceScope 方法
        f.AppendLine($"private {GlobalNames.IScope}? GetServiceScope()");
        f.BeginBlock();
        {
            f.AppendLine("if (_serviceScope is not null)");
            f.BeginBlock();
            {
                f.AppendLine("return _serviceScope;");
            }
            f.EndBlock();
            f.AppendLine();

            f.AppendLine("var parent = GetParent();");
            f.AppendLine("while (parent is not null)");
            f.BeginBlock();
            {
                f.AppendLine($"if (parent is {GlobalNames.IScope} scope)");
                f.BeginBlock();
                {
                    f.AppendLine("_serviceScope = scope;");
                    f.AppendLine("return _serviceScope;");
                }
                f.EndBlock();
                f.AppendLine("parent = parent.GetParent();");
            }
            f.EndBlock();

            f.AppendLine(
                $"{GlobalNames.GodotGD}.PushError(\"{type.Symbol.Name} 没有最近的 Service Scope\");"
            );
            f.AppendLine("return null;");
        }
        f.EndBlock();
        f.AppendLine();

        // AttachToScope 方法
        f.AppendLine("private void AttachToScope()");
        f.BeginBlock();
        {
            f.AppendLine("var scope = GetServiceScope();");
            f.AppendLine("if (scope is null) return;");

            if (type.Role == TypeRole.Host || type.Role == TypeRole.HostAndUser)
            {
                f.AppendLine("AttachHostServices(scope);");
            }

            if (type.Role == TypeRole.User || type.Role == TypeRole.HostAndUser)
            {
                f.AppendLine("ResolveUserDependencies(scope);");
            }
        }
        f.EndBlock();
        f.AppendLine();

        // UnattachToScope 方法
        f.AppendLine("private void UnattachToScope()");
        f.BeginBlock();
        {
            f.AppendLine("var scope = GetServiceScope();");
            f.AppendLine("if (scope is null) return;");

            if (type.Role == TypeRole.Host || type.Role == TypeRole.HostAndUser)
            {
                f.AppendLine("UnattachHostServices(scope);");
            }
        }
        f.EndBlock();
        f.AppendLine();

        // _Notification 方法
        f.AppendLine("public override void _Notification(int what)");
        f.BeginBlock();
        {
            f.AppendLine("base._Notification(what);");
            f.AppendLine("switch ((long)what)");
            f.BeginBlock();
            {
                f.AppendLine("case NotificationEnterTree:");
                f.BeginBlock();
                {
                    f.AppendLine("AttachToScope();");
                    f.AppendLine("break;");
                }
                f.EndBlock();

                f.AppendLine("case NotificationExitTree:");
                f.BeginBlock();
                {
                    f.AppendLine("UnattachToScope();");
                    f.AppendLine("_serviceScope = null;");
                    f.AppendLine("break;");
                }
                f.EndBlock();
            }
            f.EndBlock();
        }
        f.EndBlock();
    }

    private static void GenerateNonNodeDICode(CodeFormatter f, TypeInfo type)
    {
        f.AppendLine($"public void ResolveDependencies({GlobalNames.IScope} scope)");
        f.BeginBlock();
        {
            f.AppendLine("ResolveUserDependencies(scope);");
        }
        f.EndBlock();
    }

    private static void GenerateHostSpecific(
        SourceProductionContext context,
        TypeInfo type,
        string namespaceName,
        string className
    )
    {
        var f = new CodeFormatter();

        f.AppendLine("// <auto-generated/>");
        f.AppendLine($"namespace {namespaceName};");
        f.AppendLine();
        f.AppendLine($"partial class {className}");
        f.BeginBlock();

        // AttachHostServices
        f.AppendLine($"private void AttachHostServices({GlobalNames.IScope} scope)");
        f.BeginBlock();
        {
            foreach (var member in type.Members)
            {
                if (
                    member.Kind == MemberKind.SingletonField
                    || member.Kind == MemberKind.SingletonProperty
                )
                {
                    foreach (var exposedType in member.ExposedTypes)
                    {
                        f.AppendLine(
                            $"scope.RegisterService<{exposedType.ToDisplayString()}>({member.Symbol.Name});"
                        );
                    }
                }
            }
        }
        f.EndBlock();
        f.AppendLine();

        // UnattachHostServices
        f.AppendLine($"private void UnattachHostServices({GlobalNames.IScope} scope)");
        f.BeginBlock();
        {
            foreach (var member in type.Members)
            {
                if (
                    member.Kind == MemberKind.SingletonField
                    || member.Kind == MemberKind.SingletonProperty
                )
                {
                    foreach (var exposedType in member.ExposedTypes)
                    {
                        f.AppendLine(
                            $"scope.UnregisterService<{exposedType.ToDisplayString()}>();"
                        );
                    }
                }
            }
        }
        f.EndBlock();

        f.EndBlock();

        context.AddSource($"{className}.DI.Host.g.cs", f.ToString());
    }

    private static void GenerateUserSpecific(
        SourceProductionContext context,
        TypeInfo type,
        string namespaceName,
        string className
    )
    {
        var injectMembersList = new System.Collections.Generic.List<MemberInfo>();

        foreach (var member in type.Members)
        {
            if (member.Kind == MemberKind.InjectField || member.Kind == MemberKind.InjectProperty)
            {
                injectMembersList.Add(member);
            }
        }

        if (injectMembersList.Count == 0)
            return;

        var f = new CodeFormatter();

        f.AppendLine("// <auto-generated/>");
        f.AppendLine($"namespace {namespaceName};");
        f.AppendLine();
        f.AppendLine($"partial class {className}");
        f.BeginBlock();

        if (type.ImplementsIServicesReady)
        {
            // 生成依赖跟踪
            f.AppendLine($"private readonly {GlobalNames.Object} _dependencyLock = new();");
            f.AppendLine(
                $"private readonly {GlobalNames.HashSet}<{GlobalNames.Type}> _unresolvedDependencies = new()"
            );
            f.BeginBlock();
            {
                foreach (var member in injectMembersList)
                {
                    f.AppendLine($"typeof({member.MemberType.ToDisplayString()}),");
                }
            }
            f.EndBlock(";");
            f.AppendLine();

            f.AppendLine("private void OnDependencyResolved<T>()");
            f.BeginBlock();
            {
                f.AppendLine("lock (_dependencyLock)");
                f.BeginBlock();
                {
                    f.AppendLine("_unresolvedDependencies.Remove(typeof(T));");
                    f.AppendLine("if (_unresolvedDependencies.Count == 0)");
                    f.BeginBlock();
                    {
                        f.AppendLine($"(({GlobalNames.IServicesReady})this).OnServicesReady();");
                    }
                    f.EndBlock();
                }
                f.EndBlock();
            }
            f.EndBlock();
            f.AppendLine();
        }

        f.AppendLine($"private void ResolveUserDependencies({GlobalNames.IScope} scope)");
        f.BeginBlock();
        {
            foreach (var member in injectMembersList)
            {
                f.AppendLine(
                    $"scope.ResolveDependency<{member.MemberType.ToDisplayString()}>(dependency =>"
                );
                f.BeginBlock();
                {
                    f.AppendLine($"{member.Symbol.Name} = dependency;");

                    if (type.ImplementsIServicesReady)
                    {
                        f.AppendLine(
                            $"OnDependencyResolved<{member.MemberType.ToDisplayString()}>();"
                        );
                    }
                }
                f.EndBlock(");");
            }
        }
        f.EndBlock();

        f.EndBlock();

        context.AddSource($"{className}.DI.User.g.cs", f.ToString());
    }

    private static void GenerateScopeCode(
        SourceProductionContext context,
        ScopeNode node,
        DiGraph graph
    )
    {
        var type = node.TypeInfo;
        var namespaceName = type.Symbol.ContainingNamespace.ToDisplayString();
        var className = type.Symbol.Name;

        GenerateScopeImplementation(context, node, graph, namespaceName, className);
    }

    private static void GenerateScopeImplementation(
        SourceProductionContext context,
        ScopeNode node,
        DiGraph graph,
        string namespaceName,
        string className
    )
    {
        var f = new CodeFormatter();

        f.AppendLine("// <auto-generated/>");
        f.AppendLine($"namespace {namespaceName};");
        f.AppendLine();
        f.AppendLine($"partial class {className}");
        f.BeginBlock();

        GenerateScopeLifecycle(f, node, graph);
        f.AppendLine();
        GenerateScopeInterface(f, node, graph);

        f.EndBlock();

        context.AddSource($"{className}.DI.Scope.g.cs", f.ToString());
    }

    private static void GenerateScopeLifecycle(CodeFormatter f, ScopeNode node, DiGraph graph)
    {
        f.AppendLine($"private {GlobalNames.IScope}? _parentScope;");
        f.AppendLine();

        // GetParentScope 方法
        f.AppendLine($"private {GlobalNames.IScope}? GetParentScope()");
        f.BeginBlock();
        {
            f.AppendLine("if (_parentScope is not null)");
            f.BeginBlock();
            {
                f.AppendLine("return _parentScope;");
            }
            f.EndBlock();
            f.AppendLine();

            f.AppendLine("var parent = GetParent();");
            f.AppendLine("while (parent is not null)");
            f.BeginBlock();
            {
                f.AppendLine($"if (parent is {GlobalNames.IScope} scope)");
                f.BeginBlock();
                {
                    f.AppendLine("_parentScope = scope;");
                    f.AppendLine("return _parentScope;");
                }
                f.EndBlock();
                f.AppendLine("parent = parent.GetParent();");
            }
            f.EndBlock();

            f.AppendLine("return null;");
        }
        f.EndBlock();
        f.AppendLine();

        // InstantiateScopeSingletons 方法
        f.AppendXmlSummary("实例化所有 Scope 约束的单例服务");
        f.AppendLine("private void InstantiateScopeSingletons()");
        f.BeginBlock();
        {
            foreach (var serviceType in node.InstantiateServices)
            {
                var serviceNode = graph.ServiceNodes.FirstOrDefault(n =>
                    SymbolEqualityComparer.Default.Equals(n.TypeInfo.Symbol, serviceType)
                );

                if (serviceNode == null)
                    continue;

                var simpleServiceName = serviceType.Name;

                if (serviceNode.TypeInfo.Lifetime == ServiceLifetime.Singleton)
                {
                    f.AppendLine($"{simpleServiceName}.CreateService(");
                    f.BeginLevel();
                    {
                        f.AppendLine("this,");
                        f.AppendLine("(instance, scope) =>");
                        f.BeginBlock();
                        {
                            f.AppendLine("_scopeSingletonInstances.Add(instance);");

                            foreach (var exposedType in serviceNode.ProvidedServices)
                            {
                                f.AppendLine(
                                    $"scope.RegisterService(({exposedType.ToDisplayString()})instance);"
                                );
                            }
                        }
                        f.EndBlock();
                    }
                    f.EndLevel();
                    f.AppendLine(");");
                }
            }
        }
        f.EndBlock();
        f.AppendLine();

        // DisposeScopeSingletons 方法
        f.AppendXmlSummary("释放所有 Scope 约束的单例服务实例");
        f.AppendLine("private void DisposeScopeSingletons()");
        f.BeginBlock();
        {
            f.AppendLine("foreach (var instance in _scopeSingletonInstances)");
            f.BeginBlock();
            {
                f.AppendLine($"if (instance is {GlobalNames.IDisposable} disposable)");
                f.BeginBlock();
                {
                    f.AppendLine("try");
                    f.BeginBlock();
                    {
                        f.AppendLine("disposable.Dispose();");
                    }
                    f.EndBlock();
                    f.AppendLine($"catch ({GlobalNames.Exception} ex)");
                    f.BeginBlock();
                    {
                        f.AppendLine($"{GlobalNames.GodotGD}.PushError(ex);");
                    }
                    f.EndBlock();
                }
                f.EndBlock();
            }
            f.EndBlock();

            f.AppendLine("_scopeSingletonInstances.Clear();");
            f.AppendLine("_singletonServices.Clear();");
        }
        f.EndBlock();
        f.AppendLine();

        // CheckWaitList 方法
        f.AppendLine("private void CheckWaitList()");
        f.BeginBlock();
        {
            f.AppendLine("if (_waiters.Count == 0)");
            f.BeginBlock();
            {
                f.AppendLine("return;");
            }
            f.EndBlock();
            f.AppendLine();

            f.AppendLine($"var sb = new {GlobalNames.StringBuilder}();");
            f.AppendLine("var first = true;");
            f.AppendLine("foreach (var type in _waiters.Keys)");
            f.BeginBlock();
            {
                f.AppendLine("if (!first)");
                f.BeginBlock();
                {
                    f.AppendLine("sb.Append(',');");
                }
                f.EndBlock();
                f.AppendLine("sb.Append(type.Name);");
                f.AppendLine("first = false;");
            }
            f.EndBlock();

            f.AppendLine(
                $"{GlobalNames.GodotGD}.PushError($\"存在未完成注入的服务类型：{{sb}}\");"
            );
            f.AppendLine("_waiters.Clear();");
        }
        f.EndBlock();
        f.AppendLine();

        // _Notification 方法
        f.AppendLine("public override void _Notification(int what)");
        f.BeginBlock();
        {
            f.AppendLine("base._Notification(what);");
            f.AppendLine();
            f.AppendLine("switch ((long)what)");
            f.BeginBlock();
            {
                f.AppendLine("case NotificationEnterTree:");
                f.AppendLine("case NotificationExitTree:");
                f.BeginBlock();
                {
                    f.AppendLine("_parentScope = null;");
                    f.AppendLine("break;");
                }
                f.EndBlock();
                f.AppendLine();

                f.AppendLine("case NotificationReady:");
                f.BeginBlock();
                {
                    f.AppendLine("InstantiateScopeSingletons();");
                    f.AppendLine("CheckWaitList();");
                    f.AppendLine("break;");
                }
                f.EndBlock();
                f.AppendLine();

                f.AppendLine("case NotificationPredelete:");
                f.BeginBlock();
                {
                    f.AppendLine("DisposeScopeSingletons();");
                    f.AppendLine("break;");
                }
                f.EndBlock();
            }
            f.EndBlock();
        }
        f.EndBlock();
    }

    private static void GenerateScopeInterface(CodeFormatter f, ScopeNode node, DiGraph graph)
    {
        // 收集所有单例服务类型
        var singletonServiceTypes = new System.Collections.Generic.HashSet<ITypeSymbol>(
            SymbolEqualityComparer.Default
        );

        foreach (var serviceType in node.InstantiateServices)
        {
            var serviceNode = graph.ServiceNodes.FirstOrDefault(n =>
                SymbolEqualityComparer.Default.Equals(n.TypeInfo.Symbol, serviceType)
            );

            if (serviceNode != null && serviceNode.TypeInfo.Lifetime == ServiceLifetime.Singleton)
            {
                foreach (var exposedType in serviceNode.ProvidedServices)
                {
                    singletonServiceTypes.Add(exposedType);
                }
            }
        }

        foreach (var hostType in node.ExpectHosts)
        {
            var hostNode = graph.HostNodes.FirstOrDefault(n =>
                SymbolEqualityComparer.Default.Equals(n.TypeInfo.Symbol, hostType)
            );

            if (hostNode != null)
            {
                foreach (var exposedType in hostNode.ProvidedServices)
                {
                    singletonServiceTypes.Add(exposedType);
                }
            }
        }

        // 收集所有瞬态服务
        var transientFactories = new System.Collections.Generic.Dictionary<ITypeSymbol, string>(
            SymbolEqualityComparer.Default
        );

        foreach (var serviceType in node.InstantiateServices)
        {
            var serviceNode = graph.ServiceNodes.FirstOrDefault(n =>
                SymbolEqualityComparer.Default.Equals(n.TypeInfo.Symbol, serviceType)
            );

            if (serviceNode != null && serviceNode.TypeInfo.Lifetime == ServiceLifetime.Transient)
            {
                foreach (var exposedType in serviceNode.ProvidedServices)
                {
                    transientFactories[exposedType] = serviceType.Name;
                }
            }
        }

        // SingletonServiceTypes 静态集合
        f.AppendLine(
            $"private static readonly {GlobalNames.HashSet}<{GlobalNames.Type}> SingletonServiceTypes = new()"
        );
        f.BeginBlock();
        {
            foreach (var serviceType in singletonServiceTypes)
            {
                f.AppendLine($"typeof({serviceType.ToDisplayString()}),");
            }
        }
        f.EndBlock(";");
        f.AppendLine();

        // TransientFactories 静态字典
        f.AppendLine(
            $"private static readonly {GlobalNames.Dictionary}<{GlobalNames.Type}, {GlobalNames.Action}<{GlobalNames.IScope}, {GlobalNames.Action}<{GlobalNames.Object}>>> TransientFactories = new()"
        );
        f.BeginBlock();
        {
            foreach (var kvp in transientFactories)
            {
                f.AppendLine($"[typeof({kvp.Key.ToDisplayString()})] = {kvp.Value}.CreateService,");
            }
        }
        f.EndBlock(";");
        f.AppendLine();

        // 实例字段
        f.AppendLine(
            $"private readonly {GlobalNames.Dictionary}<{GlobalNames.Type}, {GlobalNames.Object}> _singletonServices = new();"
        );
        f.AppendLine(
            $"private readonly {GlobalNames.HashSet}<{GlobalNames.Object}> _scopeSingletonInstances = new();"
        );
        f.AppendLine(
            $"private readonly {GlobalNames.Dictionary}<{GlobalNames.Type}, {GlobalNames.List}<{GlobalNames.Action}<{GlobalNames.Object}>>> _waiters = new();"
        );
        f.AppendLine();

        // ResolveDependency 方法
        f.AppendLine(
            $"void {GlobalNames.IScope}.ResolveDependency<T>({GlobalNames.Action}<T> onResolved)"
        );
        f.BeginBlock();
        {
            f.AppendLine("var type = typeof(T);");
            f.AppendLine();

            f.AppendLine(
                "if (TransientFactories.TryGetValue(type, out var factory))",
                "尝试从瞬态工厂创建"
            );
            f.BeginBlock();
            {
                f.AppendLine("factory.Invoke(this, instance => onResolved.Invoke((T)instance));");
                f.AppendLine("return;");
            }
            f.EndBlock();
            f.AppendLine();

            f.AppendLine("if (!SingletonServiceTypes.Contains(type))", "检查是否是单例服务类型");
            f.BeginBlock();
            {
                f.AppendLine("var parent = GetParentScope();", "尝试从父 Scope 解析");
                f.AppendLine("if (parent is not null)");
                f.BeginBlock();
                {
                    f.AppendLine("parent.ResolveDependency(onResolved);");
                    f.AppendLine("return;");
                }
                f.EndBlock();
                f.AppendLine();

                f.AppendLine(
                    $"{GlobalNames.GodotGD}.PushError($\"直到根 Service Scope 都无法找到服务类型：{{type.Name}}\");"
                );
                f.AppendLine("return;");
            }
            f.EndBlock();
            f.AppendLine();

            f.AppendLine(
                "if (_singletonServices.TryGetValue(type, out var singleton))",
                "尝试从已注册的单例获取"
            );
            f.BeginBlock();
            {
                f.AppendLine("onResolved.Invoke((T)singleton);");
                f.AppendLine("return;");
            }
            f.EndBlock();
            f.AppendLine();

            f.AppendLine("if (!_waiters.TryGetValue(type, out var waiterList))", "加入等待列表");
            f.BeginBlock();
            {
                f.AppendLine(
                    $"waiterList = new {GlobalNames.List}<{GlobalNames.Action}<{GlobalNames.Object}>>();"
                );
                f.AppendLine("_waiters[type] = waiterList;");
            }
            f.EndBlock();
            f.AppendLine("waiterList.Add(obj => onResolved.Invoke((T)obj));");
        }
        f.EndBlock();
        f.AppendLine();

        // RegisterService 方法
        f.AppendLine($"void {GlobalNames.IScope}.RegisterService<T>(T instance)");
        f.BeginBlock();
        {
            f.AppendLine("var type = typeof(T);");
            f.AppendLine();

            f.AppendLine("if (!SingletonServiceTypes.Contains(type))", "检查是否是单例服务类型");
            f.BeginBlock();
            {
                f.AppendLine("var parent = GetParentScope();", "尝试向父 Scope 注册");
                f.AppendLine("if (parent is not null)");
                f.BeginBlock();
                {
                    f.AppendLine("parent.RegisterService(instance);");
                    f.AppendLine("return;");
                }
                f.EndBlock();
                f.AppendLine();

                f.AppendLine(
                    $"{GlobalNames.GodotGD}.PushError($\"直到根 Service Scope 都无法注册服务类型：{{type.Name}}\");"
                );
                f.AppendLine("return;");
            }
            f.EndBlock();
            f.AppendLine();

            f.AppendLine("if (!_singletonServices.TryAdd(type, instance))", "注册服务");
            f.BeginBlock();
            {
                f.AppendLine(
                    $"{GlobalNames.GodotGD}.PushError($\"重复注册类型: {{type.Name}}。\");"
                );
                f.AppendLine("return;");
            }
            f.EndBlock();
            f.AppendLine();

            f.AppendLine("if (_waiters.Remove(type, out var waiterList))", "通知等待者");
            f.BeginBlock();
            {
                f.AppendLine("foreach (var callback in waiterList)");
                f.BeginBlock();
                {
                    f.AppendLine("callback.Invoke(instance);");
                }
                f.EndBlock();
            }
            f.EndBlock();
        }
        f.EndBlock();
        f.AppendLine();

        // UnregisterService 方法
        f.AppendLine($"void {GlobalNames.IScope}.UnregisterService<T>()");
        f.BeginBlock();
        {
            f.AppendLine("var type = typeof(T);");
            f.AppendLine();

            f.AppendLine("if (!SingletonServiceTypes.Contains(type))", "检查是否是单例服务类型");
            f.BeginBlock();
            {
                f.AppendLine("var parent = GetParentScope();", "尝试从父 Scope 注销");
                f.AppendLine("if (parent is not null)");
                f.BeginBlock();
                {
                    f.AppendLine("parent.UnregisterService<T>();");
                    f.AppendLine("return;");
                }
                f.EndBlock();
                f.AppendLine();

                f.AppendLine(
                    $"{GlobalNames.GodotGD}.PushError($\"直到根 Service Scope 都无法注销服务类型：{{type.Name}}\");"
                );
                f.AppendLine("return;");
            }
            f.EndBlock();
            f.AppendLine();

            f.AppendLine("_singletonServices.Remove(type);");
        }
        f.EndBlock();
    }
}
