using System.Text;
using GodotSharp.DI.Shared;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace GodotSharp.DI.Generator.Internal.Coding;

internal static class UserGenerator
{
    private static string FormatType(ITypeSymbol type)
    {
        return type.ToDisplayString(DisplayFormats.TypeFormat);
    }

    public static void Generate(SourceProductionContext context, ServiceGraph graph)
    {
        foreach (var user in graph.Users)
        {
            var source = GenerateUserSource(user);
            if (source is null)
                continue;

            var hintName = $"{user.Symbol.Name}.DI.User.g.cs";
            context.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string GenerateUserSource(TypeInfo user)
    {
        var f = new CodeFormatter();

        var ns = user.Namespace;
        var typeName = user.Symbol.Name;

        f.AppendLine("// <auto-generated />");
        f.AppendLine();
        f.AppendLine($"namespace {ns};");
        f.AppendLine();

        f.AppendLine($"partial class {typeName}");
        f.BeginBlock();
        {
            // 如果实现了 IServicesReady，则生成依赖跟踪
            if (user.IsServicesReady && user.InjectedMembers.Count > 0)
            {
                f.AppendLine("private readonly global::System.Object _dependencyLock = new();");
                f.AppendLine(
                    $"private readonly global::System.Collections.Generic.HashSet<global::System.Object> _unresolvedDependencies = new()"
                );
                f.BeginBlock();
                {
                    foreach (var dep in user.InjectedMembers)
                    {
                        var depType = FormatType(dep.MemberType);
                        f.AppendLine($"typeof({depType}),");
                    }
                }
                f.EndBlock(";");
                f.AppendLine();

                f.AppendLine($"private void OnDependencyResolved(global::System.Object type)");
                f.BeginBlock();
                {
                    f.AppendLine("lock (_dependencyLock)");
                    f.BeginBlock();
                    {
                        f.AppendLine("_unresolvedDependencies.Remove(type);");
                        f.AppendLine("if (_unresolvedDependencies.Count == 0)");
                        f.BeginBlock();
                        {
                            f.AppendLine(
                                $"(({TypeNamesGlobal.ServicesReadyInterface})this).OnServicesReady();"
                            );
                        }
                        f.EndBlock();
                    }
                    f.EndBlock();
                }
                f.EndBlock();
                f.AppendLine();
            }

            // ResolveUserDependencies
            f.AppendLine(
                $"private void ResolveUserDependencies({TypeNamesGlobal.ScopeInterface} scope)"
            );
            f.BeginBlock();
            {
                foreach (var dep in user.InjectedMembers)
                {
                    var depType = FormatType(dep.MemberType);
                    var memberName = dep.MemberName;

                    f.AppendLine($"scope.ResolveDependency<{depType}>(dependency =>");
                    f.BeginBlock();
                    {
                        f.AppendLine($"{memberName} = dependency;");
                        if (user.IsServicesReady)
                        {
                            f.AppendLine($"OnDependencyResolved(typeof({depType}));");
                        }
                    }
                    f.EndBlock(");");
                }
            }
            f.EndBlock();
        }
        f.EndBlock();

        return f.ToString();
    }
}
