//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GodotSharp.DI.Generator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GodotSharp.DI.Generator.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &apos;{0}&apos; has multiple constructors but no [InjectConstructor] is specified.
        /// </summary>
        internal static string AmbiguousConstructor {
            get {
                return ResourceManager.GetString("AmbiguousConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circular dependency detected: {0}.
        /// </summary>
        internal static string CircularDependencyDetected {
            get {
                return ResourceManager.GetString("CircularDependencyDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DI-relative class &apos;{0}&apos; must be declared as partial to enable code generation.
        /// </summary>
        internal static string DiClassMustBePartial {
            get {
                return ResourceManager.GetString("DiClassMustBePartial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposed type &apos;{0}&apos; is a concrete class. Consider using an interface instead for better testability and loose coupling.
        /// </summary>
        internal static string ExposedTypeShouldBeInterface {
            get {
                return ResourceManager.GetString("ExposedTypeShouldBeInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error in source generator: {0}.
        /// </summary>
        internal static string GeneratorInternalError {
            get {
                return ResourceManager.GetString("GeneratorInternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host &apos;{0}&apos; cannot use [{1}].
        /// </summary>
        internal static string HostInvalidAttribute {
            get {
                return ResourceManager.GetString("HostInvalidAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host &apos;{0}&apos; must inherit from Godot.Node.
        /// </summary>
        internal static string HostMustBeNode {
            get {
                return ResourceManager.GetString("HostMustBeNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Singleton] member &apos;{0}&apos; has type &apos;{1}&apos;, which is already marked as a Service ([Singleton] or [Transient]). Host should not hold Service instances directly.
        /// </summary>
        internal static string HostSingletonMemberIsServiceType {
            get {
                return ResourceManager.GetString("HostSingletonMemberIsServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is not a Service but uses [InjectConstructor].
        /// </summary>
        internal static string InjectConstructorAttributeIsInvalid {
            get {
                return ResourceManager.GetString("InjectConstructorAttributeIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inject constructor parameter must be an interface type, or a non-Node, non-Host, non-User and non-Scope class type.
        /// </summary>
        internal static string InjectConstructorParameterTypeInvalid {
            get {
                return ResourceManager.GetString("InjectConstructorParameterTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injected member in &apos;{0}&apos; has type &apos;{1}&apos;, which is not a Service.
        /// </summary>
        internal static string InjectMemberInvalidType {
            get {
                return ResourceManager.GetString("InjectMemberInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Inject] member &apos;{0}&apos; has type &apos;{1}&apos;, which is a [Host] type and cannot be injected.
        /// </summary>
        internal static string InjectMemberIsHostType {
            get {
                return ResourceManager.GetString("InjectMemberIsHostType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Inject] member &apos;{0}&apos; has type &apos;{1}&apos;, which is an IScope type and cannot be injected.
        /// </summary>
        internal static string InjectMemberIsScopeType {
            get {
                return ResourceManager.GetString("InjectMemberIsScopeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Inject] member &apos;{0}&apos; cannot be static.
        /// </summary>
        internal static string InjectMemberIsStatic {
            get {
                return ResourceManager.GetString("InjectMemberIsStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Inject] member &apos;{0}&apos; has type &apos;{1}&apos;, which is a [User] type and cannot be injected.
        /// </summary>
        internal static string InjectMemberIsUserType {
            get {
                return ResourceManager.GetString("InjectMemberIsUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Inject] member must be writable (field must not be readonly, property must have setter).
        /// </summary>
        internal static string InjectMemberNotAssignable {
            get {
                return ResourceManager.GetString("InjectMemberNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not manually call generated method &apos;{0}&apos; on &apos;{1}&apos;. This method is managed by the DI framework and will be called automatically at the appropriate time.
        /// </summary>
        internal static string ManualCallGeneratedMethod {
            get {
                return ResourceManager.GetString("ManualCallGeneratedMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Singleton] and [Inject] cannot be applied to the same member.
        /// </summary>
        internal static string MemberConflictWithSingletonAndInject {
            get {
                return ResourceManager.GetString("MemberConflictWithSingletonAndInject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; must be marked as [User] to use [Inject] on members.
        /// </summary>
        internal static string MemberHasInjectButNotInUser {
            get {
                return ResourceManager.GetString("MemberHasInjectButNotInUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; must be marked as [Host] to use [Singleton] on members.
        /// </summary>
        internal static string MemberHasSingletonButNotInHost {
            get {
                return ResourceManager.GetString("MemberHasSingletonButNotInHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &apos;{0}&apos; must define at least one constructor.
        /// </summary>
        internal static string NoPublicConstructor {
            get {
                return ResourceManager.GetString("NoPublicConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator receives cancellation request: {0}.
        /// </summary>
        internal static string RequestCancellation {
            get {
                return ResourceManager.GetString("RequestCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope &apos;{0}&apos; cannot use [{1}].
        /// </summary>
        internal static string ScopeInvalidAttribute {
            get {
                return ResourceManager.GetString("ScopeInvalidAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope &apos;{0}&apos; Unexpectedly loses [Modules] or [AutoModules].
        /// </summary>
        internal static string ScopeLosesAttributeUnexpectedly {
            get {
                return ResourceManager.GetString("ScopeLosesAttributeUnexpectedly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope &apos;{0}&apos; must specify either [Modules] or [AutoModules].
        /// </summary>
        internal static string ScopeMissingModules {
            get {
                return ResourceManager.GetString("ScopeMissingModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope &apos;{0}&apos; Modules Host type &apos;{1}&apos; must be a Host.
        /// </summary>
        internal static string ScopeModulesHostMustBeHost {
            get {
                return ResourceManager.GetString("ScopeModulesHostMustBeHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope &apos;{0}&apos; specifies no Host type in [Modules] Hosts.
        /// </summary>
        internal static string ScopeModulesHostsEmpty {
            get {
                return ResourceManager.GetString("ScopeModulesHostsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope &apos;{0}&apos; Modules Service type &apos;{1}&apos; must be a Service.
        /// </summary>
        internal static string ScopeModulesServiceMustBeService {
            get {
                return ResourceManager.GetString("ScopeModulesServiceMustBeService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope &apos;{0}&apos; must specify at least one type in [Modules] Services.
        /// </summary>
        internal static string ScopeModulesServicesEmpty {
            get {
                return ResourceManager.GetString("ScopeModulesServicesEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope &apos;{0}&apos; must inherit from Godot.Node.
        /// </summary>
        internal static string ScopeMustBeNode {
            get {
                return ResourceManager.GetString("ScopeMustBeNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &apos;{0}&apos; has constructor parameter of type &apos;{1}&apos;, which is not a Service.
        /// </summary>
        internal static string ServiceConstructorParameterInvalid {
            get {
                return ResourceManager.GetString("ServiceConstructorParameterInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; implements IServicesReady but is not marked with [User].
        /// </summary>
        internal static string ServiceReadyNeedUser {
            get {
                return ResourceManager.GetString("ServiceReadyNeedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service type &apos;{0}&apos; is registered by multiple providers: {1}. Each service type must have exactly one provider within a Scope.
        /// </summary>
        internal static string ServiceTypeConflict {
            get {
                return ResourceManager.GetString("ServiceTypeConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &apos;{0}&apos; cannot inherit from Godot.Node, and must be non-abstract, non-static class type.
        /// </summary>
        internal static string ServiceTypeIsInvalid {
            get {
                return ResourceManager.GetString("ServiceTypeIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Singleton] member &apos;{0}&apos; cannot be static.
        /// </summary>
        internal static string SingletonMemberIsStatic {
            get {
                return ResourceManager.GetString("SingletonMemberIsStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Singleton] property must have a getter.
        /// </summary>
        internal static string SingletonPropertyNotAccessible {
            get {
                return ResourceManager.GetString("SingletonPropertyNotAccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown DI Type Role.
        /// </summary>
        internal static string UnknownTypeRole {
            get {
                return ResourceManager.GetString("UnknownTypeRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &apos;{0}&apos; must inherit from Godot.Node.
        /// </summary>
        internal static string UserMustBeNode {
            get {
                return ResourceManager.GetString("UserMustBeNode", resourceCulture);
            }
        }
    }
}
